channels:
  - conda-forge
  - defaults
dependencies:
  - gxx_linux-64
  - pip==24.0
  - pip:
    - ai4bharat-transliteration
    - arabic_buckwalter_transliteration
    - editdistance
    - gtts
    - opencc
    - pandas
    - pinyin
    - plotly
    - pykakasi
    - scikit-learn
    - stanza
    - streamlit
    - transliterate 
